### PR TITLE
fix: avoid treating double-dash as a param

### PR DESCRIPTION
**Pull request by Shuunen**
Hi again :)

I needed to pass params to my app like a `target` arg for exemple : `ts-run my-app.ts --target=foobar`

But I got the error `error: unknown option '--target=foobar'`, here `ts-run` is right, `target` is not a known arg

So I used the standard way to give params to the child, via double dash : `ts-run my-app.ts -- --target=foobar`

But the double dash was also transmitted to child, I added this filter to prevent this

Let me know if it's ok or if you have a better suggestion 

Regards

### CODE REVIEW

**Comment by Shuunen** [comment]
I also found the issue #3 

Your code was : 

```js
 let parentArgs;
  if (process.argv.includes("-w") || process.argv.includes("--watch")) {
    parentArgs = process.argv.slice(3, process.argv.indexOf("-w"));
  } else {
    parentArgs = process.argv.slice(3);
  }
```

So ` if (process.argv.includes("-w") || process.argv.includes("--watch")` then below you cut argv only on `process.argv.indexOf("-w")`

I simplified the code to cut on the double-dash so you can call `ts-run` like : 

- `ts-run my-app.ts`
- `ts-run my-app.ts -w my-folder`
- `ts-run my-app.ts --watch my-folder`
- `ts-run my-app.ts -w my-folder -- --param-for-my-app=foobar`
- `ts-run my-app.ts --watch my-folder -- --param-for-my-app=foobar`

So it's backward compatible, fix the -w / --watch issue & let people give args to executed ts file

**Comment by Shuunen** [comment]
Here is a project to reproduce : https://stackblitz.com/edit/node-phgydq 

With the actual implementation :

```text
❯ npm run watch-ok
$ ts-run src -w foobar
Node.js v14.19.0
Date is 3/23/2022, 7:28:59 PM
I received : [
  '/usr/local/bin/node',
  '/home/projects/node-phgydq/src/.temp-bundle.ts-run.js'
]
[ts-run]: watching for file changes in foobar
```

Here everything run fine.

```text
❯ npm run watch-not-ok
$ ts-run src --watch foobar
Node.js v14.19.0
Date is 3/23/2022, 7:29:06 PM
I received : [
  '/usr/local/bin/node',
  '/home/projects/node-phgydq/src/.temp-bundle.ts-run.js',
  '--watch'
]
[ts-run]: watching for file changes in foobar
```

Here the issue is that `'--watch'` is given as a param to the child, the issue #3 I describe above

```text
❯ npm run watch-not-working
$ ts-run src --watch foobar -- --custom-arg=12
Node.js v14.19.0
Date is 3/23/2022, 7:29:12 PM
I received : [
  '/usr/local/bin/node',
  '/home/projects/node-phgydq/src/.temp-bundle.ts-run.js',
  '--watch',
  'foobar',
  '--'
]
[ts-run]: watching for file changes in foobar
````

Here the real problem : lot of params given to the child, none is relevant and the important one `--custom-arg=12` is not given

**Comment by Shuunen** [comment]
here is the test suite I used to check my function : 

```js
function paramsForChild(args) {
    if (args.includes('--'))
        return args.slice(args.indexOf('--') + 1)
    else if (args.includes('-w') || args.includes('--watch'))
        return args.slice(Math.max(args.indexOf('-w'), args.indexOf('--watch')) + 2)
    return []
}

function expect(input, output) {
    const outputString = JSON.stringify(output)
    const actual = paramsForChild(input)
    const actualString = JSON.stringify(actual)
    console.assert(outputString === actualString, input, 'gived', actual, 'instead of', output)
}

function start() {
    console.clear()
    expect(['a', 'b'], [])
    expect(['a', 'b', '-w', 'folder'], [])
    expect(['a', 'b', '--watch', 'folder'], [])
    expect(['a', 'b', '--', '--custom-args', '12'], ['--custom-args', '12'])
    expect(['a', 'b', '--', '--custom-args', '12'], ['--custom-args', '12'])
    expect(['a', 'b', '--watch', 'folder', '--', '--custom-args', '12'], ['--custom-args', '12'])
    expect(['a', 'b', '-w', 'folder', '--', '--custom-args', '12'], ['--custom-args', '12'])
}

start()
```

**Review by saurabhdaware — COMMENTED** [review]
This is amazing! Thank you for the PR. I am on vacation since last week. 

Will check the PR this tuesday :D

**Review by saurabhdaware — APPROVED** [review]
Yay thank you so much for the PR! It's working great!!

**Comment by saurabhdaware** [comment]
Published in v0.1.1

**Comment by Shuunen** [comment]
> Yay thank you so much for the PR! It's working great!!

Glad to help 😊👍

**Pull request merged**
